kind: pipeline
name: default

steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: linter
    image: "golang:latest"
    commands:
      - export GOPROXY="https://goproxy.io"
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run

  - name: docker
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/lib/docker
    settings:
      repo: cnych/drone-k8s-demo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      use_cache: true

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker
