workspace:
  base: /go
  path: src/github.com/Depado/dummy

pipeline:
  prerequisites:
    image: "golang:latest"
    commands:
      - go version
      - export GOPROXY="https://goproxy.io"

  build:
    image: "golang:latest"
    commands:
      - go build

 linter:
    image: "golang:latest"
    commands:
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run

