kind: pipeline
name: default

steps:
  - name: linter
    image: "golang:latest"
    commands:
      - export GOPROXY="https://goproxy.io"
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - ls $GOPATH/pkg
      - golangci-lint run

  - name: docker
    image: "docker:latest"
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      repo: cnych/drone-k8s-demo
      use_cache: true
      cache_from: cnych/drone-k8s-demo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
