kind: pipeline
name: default

steps:
  - name: linter
    image: "golang:latest"
    commands:
      - export GOPROXY="https://goproxy.io"
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run

  - name: docker
    image: plugins/docker
    settings:
      repo: cnych/drone-k8s-demo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
