# 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.label.companyName }}-service
  labels:
    app: ipm
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.label.companyName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}  
      #nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.label.companyName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.label.companyName }}
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
      - name: {{ .Release.Name }}-{{ .Values.label.companyName }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }} #DataProcessing_v1.2.0.0-runtime-1.0
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: {{ .Release.Name }}-{{ .Values.label.companyName }}-volume
          mountPath: {{ .Values.volume.containerMountPath }}
      volumes:
      - name: {{ .Release.Name }}-{{ .Values.label.companyName }}-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.label.companyName }}-pvc
---
