apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.label.companyName }}-volume
  labels:
    app: ipm
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath: # PUT Config.xml IN THIS DIRECTORY. LOG FILES WILL ALSO BE STORED IN HERE
    path: {{ .Values.volume.hostMountPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: # SET YOUR K8S NODE HOSTNAME ACCORDINGLY
          - {{ .Values.nodeSelector }}

---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Release.Name }}-{{ .Values.label.companyName }}-pvc
  labels:
    app: ipm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi