# Default values for ipm-dataprocessing-master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

label:
  companyName: worker7
  app: ipm-ob-dataprocessing-master

image:
  repository: repository.imrc.be
  name: ipm
  version: DataProcessing_v1.2.0.1-ob-net227-runtime-1.1
  pullPolicy: IfNotPresent

imagePullSecrets: regcred
nameOverride: ""
fullnameOverride: ""

service:
  clusterIP: "10.110.20.11"
  type: ClusterIP
  # type: NodePort
  port: 80
  targetPort: 80
  #nodePort: 30211

volume:
  containerMountPath: 'C:\app\App_Data'
  hostMountPath: 'C:\ipm-data\dataprocessing\master'

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: master2-ubuntu

tolerations: []

affinity: {}
